name: smooth_star_rating
description: A smooth rating bar that supports full and half rating with easy icon customizability
version: 1.1.1
homepage: https://github.com/thangmam/smoothratingbar.git

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.8.1"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.4