name: smooth_star_rating
description: A smooth rating bar that supports full and half rating with easy icon customizability
version: 1.1.1
homepage: https://github.com/thangmam/smoothratingbar.git

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter